#' Imports annotation from reannotation mapping
#'
#' \code{import_reanno} adds reannotation to PAC.
#'
#' Given the path to reannotation files (reanno_mis0/1/2/3/4/5.Rdata) generated
#' by functions in the PAC reannotation family, this function will summarize the
#' reannotation files into one output. Optionally a PAC object can be provided,
#' in which case the function will attempt to merge the new reannotation to the
#' existing Anno data.frame of the PAC object.
#'
#' @family PAC reannotation
#'
#' @seealso \url{https://github.com/junchaoshi/sports1.0} for download and
#'   documentation about running Sports.
#'   \url{http://bowtie-bio.sourceforge.net/index.shtml} for information about
#'   Bowtie \url{https://github.com/Danis102} for updates on the current
#'   package.
#'
#' @param reanno_path Path to a directory where reannotation .Rdata files can be
#'   found.
#' @param PAC PAC-list object containing an Anno data.frame with sequences as
#'   row names.
#' @param mis_fasta_check Logical TRUE/FALSE if checking against anno_misX.fa
#'   should be done.
#'
#' @return Data.frame with additional information from reannotation using
#'   bowtie. If \emph{PAC} is specified, the function will return the specifed
#'   PAC object with an added reannotation column in the Anno data.frame.
#'   If \emph{mis_fasta_check} is specified the function will look for a
#'   \emph{anno_misX.fa} (X = the file with the highest number) previoulsy
#'   generated by the reannotation workflow. This file is used to double check
#'   so that no sequences are missing before and after reannotation.
#'
#'
#' @examples
#' reanno <- add_reanno(reanno_path, PAC=PAC, mis_fasta_check=TRUE)    # Complete use
#'
#' @export

add_reanno <- function(reanno_path, PAC=NULL, mis_fasta_check=FALSE){
                  require(plyr)
              cat("First reading the reannotation files ...\n")
                  files <- list.files(reanno_path, pattern="reanno_mis0|reanno_mis1|reanno_mis2|reanno_mis3|reanno_mis4|reanno_mis5", full.names = TRUE)
                  seqs <- (seq(1:length(files)))-1
                  reanno_lst <- list(NA)
                  for(i in 1:length(files)){load(files[i])
                                            reanno_lst[[i]] <- data.table::rbindlist(reanno, idcol=TRUE)
                                            names(reanno_lst) <- paste0("mis", seqs[i])
                                            }
              cat("Compiling everything into one data.frame ...\n")
                  reanno_long <- as.data.frame(data.table::rbindlist(reanno_lst, idcol=TRUE))
                  reanno_long$anno <- paste(reanno_long[,2], reanno_long[,1], sep="|")
                  reanno_long <- reanno_long[,c(3,5)]
              cat("Collapsing sequences that multimap between different references ... (may take some minutes)\n")
                  reanno_short <- ddply(reanno_long, .(seq), function(x) paste(unique(x[,"anno"]), collapse="; "))
                  colnames(reanno_short)[2] <- "reannotation"
                  reanno_short$seq <- as.character(reanno_short$seq)
                  reanno_short$reannotation <- as.character(reanno_short$reannotation)
            if(is.null(PAC)){return(reanno_short)}
            if(!is.null(PAC)){
              cat("PAC object was specified. Will attempt to merge reannotation with existing Anno data.frame ... \n")
                  len_anno <- nrow(PAC$Anno)
                  hits_reanno <- sum(rownames(PAC$Anno) %in% reanno_short$seq)

              cat("Of ", len_anno, "uniques sequences in PAC\n")
              cat(hits_reanno, "(", round(hits_reanno/len_anno*100, digits=2), "%) was represented in the reannotation files.\n")
            if(mis_fasta_check==TRUE){
              cat("\nAn anno_mis_fasta file was specified by user, will try to read this file from same directory as the reannotion files.\n")
                  anno_mis_fls <- list.files(reanno_path, pattern = "anno_mis\\d.fa")
                  ns <- max(as.integer(gsub("anno_mis|.fa", "", anno_mis_fls)))
                  file_nam <- paste0("anno_mis", ns, ".fa")
                  noAnno_fasta <- Biostrings::readDNAStringSet(paste0(reanno_path,"/", file_nam))
                  noAnno_PAC <- data.frame(seq=rownames(PAC$Anno)[!rownames(PAC$Anno) %in% reanno_short$seq], reannotation="noAnno")
                  hits_noAnno <- sum(as.character(noAnno_PAC$seq) %in% paste0(noAnno_fasta))
                     cat("Of the ", nrow(noAnno_PAC), "missing sequences in the reannotation files\n")
                     cat(paste0(hits_noAnno, " (", round(hits_noAnno/nrow(noAnno_PAC)*100, digits=2), "%) were found in ", file_nam, "\n"))
                        if(!hits_noAnno-nrow(noAnno_PAC)==0){warning(paste0("Not all missing annotations were found in ", file_nam, ". This indicates that something has gone wrong in the reannotation workflow.\n"))}
                        if(hits_noAnno-nrow(noAnno_PAC)==0){cat("Good! This is how it should be...\n")}
                  }
                reanno_fin <- data.table::rbindlist(list(reanno_short, noAnno_PAC))
                stopifnot(any(rownames(PAC$Anno) %in% reanno_fin$seq))
              cat("Matching and merging PAC with reannotation ... \n")
                reanno_fin_ord <- as.data.frame(reanno_fin[match(rownames(PAC$Anno), reanno_fin$seq),])
                rownames(reanno_fin_ord) <- reanno_fin_ord$seq
                PAC$Anno <- cbind(PAC$Anno, reanno_fin_ord)
                stopifnot(identical(as.character(PAC$Anno$seq), rownames(PAC$Anno)))
                PAC$Anno <- PAC$Anno[,"seq"]
                return(PAC)
              cat("Done.\n")
              }
          }





