#' Checks annotation from reannotation mapping
#'
#' \code{check_reanno} check if names are available in reanno import.
#'
#' Given the path to bowtie mapping output, \code{\link{import_reanno}} will attempt to
#' read these files into R and generate a list of unordered data.frames where
#' each row summarizes all annotations for a given sequence. \code{check_reanno}
#' will check if sequences are listed in any of the imported reannotation
#' data.frames. \code{\link{add_reanno}} will add the new annotations to a PAC-list
#' object.
#'
#' @family PAC reannotation
#'
#' @seealso \url{https://github.com/junchaoshi/sports1.0} for download and
#'   documentation about running Sports.
#' @seealso \url{http://bowtie-bio.sourceforge.net/index.shtml} for information about
#'   Bowtie.
#' @seealso \url{https://github.com/Danis102} for updates on the current
#'   package.
#'
#' @param anno PAC-list object or annotation data.frame with sequences as row
#'   names.
#' @param reanno reannotation list generated by \code{import_reanno}.
#' @param threads Integer stating the number of parallell jobs.
#'
#' @return logical vector stating if an anno sequences is present (TRUE)  or
#'   absent (FALSE) in reanno.
#'
#' @examples
#' reanno <- import_reanno(bowtie_path=<your_path_to_bowtie_output_directory>, threads=8)
#' reanno <- import_reanno(bowtie_path="/data/Data_analysis/Projects/Drosophila/Other/IOR/Joint_analysis/R_analysis/reanno", threads=8)
#' 
#' bowtie_path <- "/data/Data_analysis/Projects/Drosophila/Specific_projects/Test_temp/Processed_Sports_09-10-19/R_files"
#' @export
check_reanno <- function(anno, reanno,  threads=1){
                          if(class(anno)=="PAC"){       anno_seqs <- rownames(anno$Anno)}
                          if(class(anno)=="list"){      anno_seqs <- rownames(anno$Anno)}
                          if(class(anno)=="data.frame"){anno_seqs <- rownames(anno)}
                          if(class(anno)=="DNAStringSet"){anno_seqs <- paste(anno)}
                          reanno_df <- rbindlist(reanno, fill=FALSE)
                          reanno_seqs <- unique(reanno_df$seq)
                          logi <- anno_seqs %in% reanno_seqs
                          return(logi)
                          }
