#' Make a Simple Annotaion File 
#'
#' \code{make_anno} makes a very simple annotation file
#' 
#' Given a Counts list object generated by \code{\link{make_counts}} this
#' function extracts sequences lengths and stores them in a data.frame.
#' 
#' @family PAC generation
#'
#' @seealso \url{https://github.com/Danis102} for updates on the current
#'   package.
#'
#' @param counts A Counts list object generated by \code{\link{make_counts}}.
#'   
#' @return
#'   Simple annotation Data.frame with sequence size (number of characters of
#'   the Counts list sequences).
#'   
#' @examples
#'
#'  anno <- make_anno(counts = counts_list)
#'
#' @export

make_anno <- function(counts){
                  if(class(counts)=="list"){cnts <- counts[["counts"]]}
                  if(class(counts)=="data.frame"){cnts <- counts}
                  anno <- data.frame(Size=nchar(rownames(cnts)))
                  rownames(anno) <- rownames(cnts)
                  return(anno)
}
