#' Make PAC
#'
#' \code{make_PAC} Compiles, order and checks the assumptions of a PAC file.
#'
#' Given a pheno, an anno and a counts data.frames the functions will safely
#' generate a simple PAC list-object.
#'
#' @family PAC generation
#'
#' @seealso \url{https://github.com/Danis102} for updates on the current
#'   package.
#'
#' @param pheno Data.frame with sample names as row names containing
#'   metadata about each sample. Can be generated by the \code{\link{make_pheno}}
#'   function.
#'
#' @param anno Data.frame with unique sequences as row names containing metadata
#'   about each sequence. If anno=NULL, a simple Anno data.frame will
#'   automatically be generated from the the sequence names in counts.
#'   Annotaions for each sequence can be extended using for example the reanno
#'   workflow (see vignette).
#'
#' @param counts Data.frame representing a counts table, with column names as
#'   sample names and sequence names as row names. Contains the counts for each
#'   sequence across the samples. Can be generated by the
#'   \code{\link{make_counts}}.
#'
#' @return Ordered PAC list object, checked for compatibility with 
#'   downstream analysis in seqpac.
#'   
#' @examples
#'
#' library(seqpac) 
#' 
#' ### First make counts 
#' 
#' 
#' input = system.file("extdata", package = "seqpac", mustWork = TRUE)
#' counts  <- make_counts(input, threads=1, parse="default_neb", type="fastq",
#'                        trimming="seqpac", plot=TRUE, evidence=c(experiment=2, sample=1))
#'
#'
#' ### Then generate a phenotype table with make_pheno (herre using file names)
#'
#' #  Note:  'Sample_ID' column need to be the same IDs as colnames in the counts table.
#'
#' pheno <- as.data.frame(do.call("rbind", strsplit(list.files(input,pattern="*.fastq.gz"), "_|\\."))[,c(1,2,3,4)]) 
#' colnames(pheno) <- c("stage", "batch", "index", "sample") 
#' pheno$Sample_ID <- apply(pheno, 1, function(x){paste(x, collapse="_")}) 
#' pheno <- make_pheno(pheno=pheno, progress_report=counts$progress_report, counts=counts$counts)
#'
#'  
#' ### Lastly combine into PAC
#' 
#' # Note: a simple annotation table will be added automatically.
#' 
#' pac <- make_PAC(pheno=pheno, counts=counts, anno=NULL)
#'
#' @export

make_PAC<- function(pheno, anno=NULL, counts){
  if(class(counts)=="list"){
    counts <- counts[["counts"]]
  }
  if(is.null(anno)){
    anno <- data.frame(Size=nchar(rownames(counts)))
    rownames(anno) <- rownames(counts)
  }
  PAC_unord <- list(Pheno=pheno, Anno=anno, Counts=counts)
  stopifnot(!any(!unlist(lapply(PAC_unord, is.data.frame))))
  stopifnot(nrow(anno) == nrow(counts))
  stopifnot(nrow(pheno) == ncol(counts))
  ph_ord <- colnames(PAC_unord$Counts)
  seq_ord <- rownames(PAC_unord$Counts)
  PAC_unord$Anno <- PAC_unord$Anno[match(rownames(PAC_unord$Anno), seq_ord),, drop=FALSE]
  PAC_unord$Pheno <- PAC_unord$Pheno[match(rownames(PAC_unord$Pheno), ph_ord),, drop=FALSE]
  class(PAC_unord) <-  c("list", "PAC")
  stopifnot(PAC_check(PAC_unord))
  return(PAC_unord)
}

                                
      
  
  
  
  
  