#' volcano plot of differential expression.
#'
#'
#' Given a PAC or a PAC_deseq result object generated by \code{PAC_deseq} this
#' function will create a volcano plot, showing fold change in relation to
#' p value, calcualted by deseq2.
#' 
#' @family PAC analysis
#'   
#' @seealso \url{https://github.com/Danis102} for updates on the current
#'   package.
#'
#' @param PAC PAC-list object, or a result object from PAC_deseq.
#'   
#'
#' @param colvec Vector for graph colours. 
#'   
#' @param manual_lab character vectors defining the rowname of
#'   specified points in volcano plot that should have labels.
#'   
#'   
#' @return vector for the graph.
#'   
#' @examples
#' 
#' 
#' 
#' @export



PAC_volcano<-function(PAC, colvec=NULL, manual_lab=NULL){
#require packages
  require(ggrepel)
  require(ggplot2)
 
#make colvec if NULL
  if(is.null(colvec)){
    bio <- as.character(unique(ann[,1]))
    n_extra  <- sum(bio %in% c("no_anno", "other"))
    colfunc <- colorRampPalette(c("#094A6B", "#FFFFCC", "#9D0014"))
    if(n_extra==1){colvec <- c(colfunc(length(bio)-1), "#6E6E6E")}
    if(n_extra==2){colvec <- c(colfunc(length(bio)-2), "#6E6E6E", "#BCBCBD")}
    if(n_extra==0){colvec <- colfunc(length(bio))}
  }
  
  #prepare data
  res<-PAC$de$result
  input<-na.omit(res)
  input$FC<-input[,3]
  
  #create the plot
  p<-ggplot(input, aes(FC, -log10(pvalue), fill=Biotypes)) + #volcanoplot with log2Foldchange versus pvalue
      geom_point(aes(col=Biotypes), alpha=3/8, size=1.5)  +
      scale_color_manual(values=colvec)+
      theme_minimal()+
      labs(x=names(input[3]), y="-log10 (P. value)", fill="Sig.")+
      theme(axis.title.x=element_text(size=15))+
      theme(axis.title.y=element_text(size=15))+
      theme(text=element_text(size=10))+
      theme(legend.title = element_text(size=15))+
      theme(legend.text = element_text(size = 10))
  
  
  #if specific labels - but add something more general here, as they may decide name of Biotype column themselves
  #not finished
  if(!is.null(manual_lab)){p+geom_text_repel(data=input[input$Biotypes %in% manual_lab,], aes(label=manual_lab), size=2)}
  
  
  return(p)  
}
