#' Pie plot from PAC
#'
#' \code{PAC_pie} analyses nucleotide bias.
#'
#' Given a PAC object the function will summarize the counts into percent
#' biotype and plot a pie chart.
#'
#' @family PAC analysis
#'
#' @seealso \url{https://github.com/Danis102} for updates on the current
#'   package.
#'
#' @param PAC PAC-list object.
#' 
#' @param anno_target List with: 
#'                          1st object being character vector of target column(s) in Anno, 
#'                          2nd object being a character vector of the target
#'                          biotype(s) in the target column (1st object).
#'                          Important, the 2nd object is order sensitive,
#'                          meaning that categories will appear in the same
#'                          order in the pie. (default=NULL)
#'
#'
#' @param pheno_target List with: 
#'                          1st object being character vector of target column(s) in Pheno, 
#'                          2nd object being a character vector of the target
#'                          group(s) in the target column (1st object).
#'                          Important, the 2nd object is order sensitive,
#'                          meaning that categories will appear in the same
#'                          order in the pie. (default=NULL)
#'
#' @param colvec Character vector RGB color codes as generated by for example
#'   grDevices::colorRampPalette. If colvec=NULL (default), colors will be
#'   generated using a default color palett. Important: In default mode,
#'   categories named "other" or no_anno" will automtically recieve a grey
#'   color.
#'
#' @param angle Integer vector (poitive or negative) that sets the rotation of
#'   the pie.
#'   
#' @return A pie plot
#'
#' @examples
#' 
#' ### Load data ###
#' path="/data/Data_analysis/Projects/Drosophila/Other/IOR/Jan_IOR_200130/R_analysis_full/"
#' load(file=paste0(path, "PAC_all.Rdata"))
#' 
#' ### Generate rpm values ###
#' PAC_all <- PAC_rpm(PAC_all)
#' 
#' ### Filter PAC file ###
#' PAC_filt <- PAC_filter(PAC_all, size = c(16, 45), threshold = 10, coverage = 50, type = "rpm", stat = TRUE, pheno_target = list("Method", c("IOR1_proto", "IOR1_tgirt")), anno_target = NULL)
#' PAC_filt <- PAC_filter(PAC_all, size = c(16, 45), threshold = 10, coverage = 10, type = "rpm", stat = TRUE, pheno_target = NULL, anno_target = NULL)
#' 
#' ### Generate hierachy of simplified biotypes ###
#' unique(do.call("c", strsplit(as.character(PAC_filt$Anno$mis0), ";|\\|")))
#' 
#' hierachy = list( rRNA="rRNA",
#'                  Mt_tRNA= "tRNA_mt-tRNA",
#'                  tRNA="Ensembl_tRNA|tRNA_nuc-tRNA",
#'                  miRNA="^miRNA|Ensembl_miRNA",
#'                  pre_miRNA="Ensembl_pre_miRNA",
#'                  snoRNA="snoRNA",
#'                  snRNA="snRNA",
#'                  lincRNA="lincRNA",
#'                  piRNA="piRNA")
#'                  
#' hierachy = list( rRNA="rRNA",
#'                  tRNA="Ensembl_tRNA|tRNA_nuc-tRNA|tRNA_mt-tRNA",
#'                  miRNA="^miRNA|Ensembl_miRNA|Ensembl_pre_miRNA",
#'                  piRNA="piRNA")
#'                  
#' PAC_filt <- simplify_reanno(PAC_filt, hierachy=hierachy, mismatches=0, bio_name="Biotypes", PAC_merge=TRUE)
#' 
#' ### Plot stacked bargraphs
#' table(PAC_filt$Anno$Biotypes)
#' unique(PAC_filt$Anno$Biotypes)
#' biotypes_ord <- c("rRNA", "tRNA", "Mt_tRNA", "miRNA", "piRNA", "snoRNA", "snRNA", "lincRNA", "no_anno")
#' biotypes_ord <- c("rRNA", "tRNA", "miRNA", "piRNA", "other", "no_anno")
#' 
#' PAC_filt$Pheno$Method_Tag <- gsub("__", "", paste(PAC_filt$Pheno$Method, PAC_filt$Pheno$Tag, sep="_"))
#' table(PAC_filt$Pheno$Method_Tag)
#' unique(PAC_filt$Pheno$Method_Tag)
#' method_ord <- c("R2_R2R","IOR1_proto","IOR1_tgirt","IOR2_Long_proto_Tag","IOR2_Short_proto_Tag", "IOR2_Long_proto_No_Tag", "IOR2_Short_proto_No_Tag")
#' 
#' plot_lst  <- PAC_pie(PAC_filt, anno_target = list("Biotypes", biotypes_ord), pheno_target = list("Method_Tag", method_ord), colvec=NULL, angle=-25)  
#' 
#' 
#' cowplot::plot_grid(plotlist=plot_lst, labels=names(plot_lst))

#'  
#'    
#' @export


PAC_pie <- function(PAC, anno_target=NULL, pheno_target=NULL, colvec=NULL, no_anno=TRUE, summary="sample", angle=-25){
  stopifnot(PAC_check(PAC))
  
  ## Prepare targets
  if(!is.null(pheno_target)){ 
    if(length(pheno_target)==1){ pheno_target[[2]] <- as.character(unique(PAC$Pheno[,pheno_target[[1]]]))
    }
  }else{
    PAC$Pheno$eXtra_Col <- rownames(PAC$Pheno)
    pheno_target <- list(NA)
    pheno_target[[1]] <-  "eXtra_Col"
    pheno_target[[2]] <-  PAC$Pheno$eXtra_Col
    }
  if(!is.null(anno_target)){ 
    if(length(anno_target)==1){ 
      anno_target[[2]] <- as.character(unique(PAC$Anno[,anno_target[[1]]]))
    }
  }

  ## Subset
  PAC_sub <- PAC_filter(PAC, subset_only=TRUE, pheno_target=pheno_target, anno_target=anno_target)
  anno <- PAC_sub$Anno
  pheno <- PAC_sub$Pheno
  data <- PAC_sub$Counts
  
  ### Removing no_Anno
  if(no_anno==FALSE){
    data <- data[!as.character(anno[, anno_target[[1]]]) == "no_anno",]
    anno <- anno[!as.character(anno[, anno_target[[1]]]) == "no_anno",]
  }
  
  ### Totaling all counts per sample and sums each per biotype
  if(summary=="all"){
    tot_cnts <- mean(colSums(data))
    names(tot_cnts) <- "all"
    data_shrt <- aggregate(data, list(anno[, anno_target[[1]]]), "sum")
    data_shrt <- data.frame(Group.1=data_shrt[,1], all= rowMeans(data_shrt[,-1])) 
    
  }else{
  
    if(summary %in% c("sample","samples","pheno", "Pheno")){
      tot_cnts <- colSums(data)
      data_shrt <- aggregate(data, list(anno[, anno_target[[1]]]), "sum")
    }
    
    if(summary %in% c("pheno", "Pheno")){
      x <- split(pheno, pheno[, pheno_target[[1]]])
      data_pheno_shrt <- as.data.frame(data_shrt$Group.1)
     for(i in 1:length(x)){
       names <- as.data.frame(x[i])
       names <- rownames(names)
       data_pheno <- data_shrt[, colnames(data_shrt) %in% names]
       data_pheno <- rowMeans(data_pheno)
       data_pheno_shrt <- as.data.frame(cbind(data_pheno_shrt,data_pheno))}
    colnames(data_pheno_shrt) <- c("Group.1", names(x))
    data_shrt <- data_pheno_shrt
    tot_cnts <- colSums(data_shrt[,-1])
    }
  }  
  
  data_shrt_perc <- data_shrt
  data_shrt_perc[,-1] <- "NA"
  for (i in 1:length(tot_cnts)){ 
    data_shrt_perc[,1+i]   <- data_shrt[,1+i]/tot_cnts[i]
  }
  
  data_long_perc <- reshape2::melt(data_shrt_perc, id.vars="Group.1")
  colnames(data_long_perc) <- c("Category", "Sample", "Percent")
  data_long_perc$Percent <- data_long_perc$Percent*100

  ## Fix order
  # Anno
  bio <- anno_target[[2]] 
  extra  <- which(bio %in% c("no_anno", "other"))
  bio <- bio[c(extra, (1:length(bio))[!1:length(bio) %in% extra])] 
  data_long_perc$Category <- factor(as.character(data_long_perc$Category), levels=bio)
    
  # Pheno
  if(is.null(pheno_target)){
    data_long_perc$Sample <- factor(as.character(data_long_perc$Sample), levels=as.character(unique(data_long_perc$Sample)))
  }else{
    if(summary %in% c("sample","samples")){
    stopifnot(any(!rownames(PAC$Pheno) %in% as.character(data_long_perc$Sample))==FALSE)
    sampl_ord <- do.call("c", split(rownames(PAC$Pheno), factor(PAC$Pheno[,pheno_target[[1]]], levels=pheno_target[[2]])))
    data_long_perc$Sample <- factor(as.character(data_long_perc$Sample), levels=as.character(sampl_ord))
    data_long_perc <- data_long_perc[!is.na(data_long_perc$Sample),]
    }
  }
  
  ## Add total counts
  # tot_cnts <- tot_cnts[match(names(tot_cnts), unique(data_long_perc$Sample))]
  # data_long_perc$tot_counts <- ""
  # if(total==TRUE){
  #   trg_1st <- levels(data_long_perc$Category)[length(levels(data_long_perc$Category))]
  #   data_long_perc$tot_counts[data_long_perc$Category == trg_1st] <- tot_cnts
  # }
  
  ### Plot data
  if(is.null(colvec)){
    n_extra  <- length(extra)
    colfunc <- grDevices::colorRampPalette(c("#094A6B", "#EBEBA6", "#9D0014"))
    if(n_extra==1){colvec <- c(colfunc(length(bio)-1), "#6E6E6E")}
    if(n_extra==2){colvec <- c(colfunc(length(bio)-2), "#6E6E6E", "#BCBCBD")}
    if(n_extra==0){colvec <- colfunc(length(bio))}
  }
  
  prec_lst <- split(data_long_perc, data_long_perc$Sample)   
  prec_lst <- lapply(prec_lst, function(x){
    x <- x[match(levels(x$Category), x$Category),]
    x$Category <- factor(levels(x$Category), levels=levels(x$Category))
    x$Percent[is.na(x$Percent)] <- 0
    return(x)
  })
  plt_lst<- invisible(lapply(prec_lst, function(x){
    p1  <- pie(x$Percent, labels=paste0(x$Category, "_", round(x$Percent, digits=0), "%"), col=rev(colvec), init.angle = angle)
    print(p1)
    rp <- recordPlot()
    return(rp)
    }))
  df <- data.frame(types=prec_lst[[1]]$Category, variables=prec_lst[[1]]$Category, levels=levels(prec_lst[[1]]$Category)) 
  leg <- cowplot::get_legend(ggplot2::ggplot(df, ggplot2::aes(x=types, fill=variables)) + 
                               ggplot2::geom_bar(color="black") + 
                               ggplot2::scale_fill_manual(values=rev(colvec))) 
  return(c(plt_lst, list(legend=leg)))
}
