#' Aligning sequences against references to produce annotation information
#'
#' Aligns sequences in a PAC list object against specified references, returning
#' a data frame or PAC object containing annotation information
#'
#' Given a PAC object, the destination of reference files, and information of
#' what type of information to save, this function will perform mapping against references
#' and retain information of mapping. This function is based of three main functions;
#'  \code{map_reanno}, \code{make_reanno} and \code{add_reanno}, whom may be ran 
#'  separately for more detailed control of the workflow. 
#'  Using save_name=TRUE in this function will retain the name of the references where sequences are found,
#'  which may cause large objects.   
#'
#' @family PAC reannotation
#'
#' @seealso  \url{http://bowtie-bio.sourceforge.net/index.shtml} for information
#'   about Bowtie and for Rbowtie:
#'   \url{https://www.bioconductor.org/packages/release/bioc/html/Rbowtie.html}.
#'   \url{https://github.com/OestLab/seqpac} for updates on the current package.
#'
#' @param PAC PAC-list object containing an Anno data.frame with sequences as
#'   row names.
#'
#' @param type Character indicating if mapping should be performed by calling
#'   the internal bowtie function of the Rbowtie package (type="internal"), or
#'   if bowtie should be called externally through a system call for a locally
#'   installed bowtie (type="external").
#'
#' @param mismatches Integer indicating the maximum number of mismatches allowed
#'   in the alignments. The function currently supports no more than 3
#'   mismatches (botwie max).
#'
#' @param output Character indicating the path to the destination folder
#'   for the files generated by the function. If no output folder is defined,
#'   files will be stored in a temporary folder and may be removed on system
#'   restart.
#'
#' @param input_genome List of file paths (character) indicating the full paths to
#'   each fasta reference file used for genome mapping. Note: All reference fasta files must have
#'   bowtie indexes using \code{Rbowtie::bowtie_build}.
#'   
#' @param input_biotype List of file paths (character) indicating the full paths to
#'   each fasta reference file used for biotype mapping. The names in this list 
#'   determines which names will be used in the final annotation. Note: All 
#'   reference fasta files must have bowtie indexes using \code{Rbowtie::bowtie_build}.
#'
#' @param threads Integer indicating the number of parallel processes to be
#'   used. 
#'   
#' @param bio_search List of character vectors indicating search terms targeting
#'  feature names in the original reference fasta files. The function will look for
#'  the bio_search terms with \code{\link{grepl}} and annotate accordingly.For
#'  more details on how this works, please see \code{\link{add_reanno}}.
#'  If bio_search is NULL, this function will try to estimate which biotypes that are present
#'  in references used by looking for characters combined with "RNA", e.g "miRNA". 
#'  This assumes the references used have named sequences in such a fasion, and may 
#'  work subpar with some references due to that.
#'   
#' @param save_name logical statement whether to report back full length names of
#' biotype annotations, useful for further annotations. The default is set to FALSE, 
#' as this may create Anno objects of wonky dimensions with certain reference .fasta files. 
#' 
#' @param hierarchy list of which hierarchy to use for biotype assignment with
#' \code{\link{simplify_reanno}}, where more details can be found on its construction. 
#' If empty, the function will provide a generalized hierarchy based off the biotypes found in the data.
#' 
#' @param filter_hit If filter_hit is TRUE, sequences without a hit to the reference
#' genome(s) defined in input_genome up until the mismatches defined will be removed.
#' Default is TRUE.
#' 
#' @param estimate_biotype if bio_search is NULL and estimate_biotype is TRUE, 
#' the function will try to estimate which biotypes are present in references
#' provided. If function should be ran with a NULL bio_search and not estimate
#' the biotypes present, estimate_biotype may be set to FALSE.
#' 
#' @param override logical whether to write over files in output folder (TRUE),
#' or whether to ask user for console input to confirm overwriting files.
#' 
#' @param ... Arguments to be passed on to \code{\link{map_reanno}}, \code{\link{make_reanno}}
#' and \code{\link{add_reanno}}.
#'   
#' @return Will return a PAC object with an expanded Anno. 
#'  
#' @examples
#' 
#' # Example for general mapping, for more advanced uses please see
#' # ?map_reanno, ?simply_reanno an ?add_reanno
#' closeAllConnections()
#' 
#' # Create an reanno object
#' 
#' ## First, if you haven't already generated Bowtie indexes for the included
#' # fasta references you need to do so. If you are having problem see the small
#' # RNA guide (vignette) for more info.
#'                                                              
#'  ## tRNA:
#'  trna_file <- system.file("extdata/trna", "tRNA.fa", 
#'                           package = "seqpac", mustWork = TRUE)
#'  trna_dir <- dirname(trna_file)
#'  
#'  if(!sum(stringr::str_count(list.files(trna_dir), ".ebwt")) ==6){     
#'      Rbowtie::bowtie_build(trna_file, 
#'                            outdir=trna_dir, 
#'                            prefix="tRNA", force=TRUE)
#'                            }
#'  ## rRNA:
#'  rrna_file <- system.file("extdata/rrna", "rRNA.fa", 
#'                           package = "seqpac", mustWork = TRUE)
#'  rrna_dir <- dirname(rrna_file)
#'  
#'  if(!sum(stringr::str_count(list.files(rrna_dir), ".ebwt")) ==6){
#'      Rbowtie::bowtie_build(rrna_file, 
#'                            outdir=rrna_dir, 
#'                            prefix="rRNA", force=TRUE)
#'                            }
#'                            
#'                            
#' ##  Then load a PAC-object and remove previous mapping from anno:
#'  load(system.file("extdata", "drosophila_sRNA_pac_filt_anno.Rdata", 
#'                    package = "seqpac", mustWork = TRUE))
#'  anno(pac) <- anno(pac)[,1, drop = FALSE]
#'  
#'  input <- list(trna= trna_file, rrna= rrna_file)
#' 
#'                                     
#' ##  You may add an output path of your choice, but here we use a temp folder:
#'  output <- paste0(tempdir(),"/seqpac/test")
#' 
#' bio_search <- list(rrna=c("5S", "5.8S", "12S", "16S", "18S", "28S", "pre_S45"),
#' trna =c("_tRNA", "mt:tRNA"))
#' 
#' pac_anno <- PAC_map(PAC=pac, output=output,
#' mismatches=0,
#' input=input, mapping="biotype", save_name=TRUE,
#' bio_search=bio_search, override=TRUE)
#' 
#' head(pac_anno)
#' 
#' @export
# 



#This version of the map provides the user with a "standardised" workflow that makes some assumptions about the
#fasta files. We should check these with some different PACs and different references if we think this is a good 
#function to use moving forward


PAC_map2 <- function(PAC, type="internal",
                    output, input_genome,
                    input_biotype, hierarchy=NULL,
                    bio_search=NULL, mismatches=3, 
                    filter_hit=TRUE, estimate_biotype=FALSE,
                    save_name=FALSE, threads=1, override=TRUE, ...){
  
  ## Check S4
  if(isS4(PAC)){
    tp <- "S4"
    PAC <- as(PAC, "list")
  }else{
    tp <- "S3"
  }
  
  if(is.null(output)){
    output <- paste0(tempdir(),"/seqpac/test")
  }
  
  reanno <- NULL
  
  #genome mapping 
  map_reanno(PAC=PAC, input=input_genome, output=output, mismatches = mismatches, override=override, ...)
  reanno_genome<-make_reanno(PAC=PAC, reanno_path=output, ...)
  PAC <- add_reanno(reanno_genome, type="genome", mismatches = mismatches, merge_pac=PAC)
  
  #filter
  if(filter_hit==TRUE){
    cat(paste0("\nSequences that did not have a hit to reference genome(s) with up to ",mismatches," mismatches will now be removed. 
If you wish to retain these, please rerun the function with filter_hit=FALSE!\n"))
    PAC <- PAC_filter(PAC, anno_target = list("Any_genome", "Hit"))
  }
  
  if(!is.null(input_biotype)){   
  
  #Biotype mapping 
  map_reanno(PAC=PAC, input=input_biotype, output=output, mismatches = mismatches, override=override, ...)
  reanno_biotype<-make_reanno(PAC=PAC, reanno_path=output, ...)
  
  #if no bio_search is given by user, and user allows us to estimate the biotype;
  #av ngn anledning skippar den denna delen :( det går bra om jag bara har en av dem, kanske är estimate_biotype som är dum
  
  
  
  #here I need to put in some work - thr naming is weird
  if(is.null(bio_search)){
     if(estimate_biotype==TRUE){
  

    cat(("\n
Biotype references have been provided in input_biotype, but no bio_search names for naming have been given. 
Since estimated_biotype=TRUE, the function will try to find relevant biotypes in references now.
\n"))
    
    ebt <- as.data.frame(reanno_biotype@Full_anno)
    rownames(ebt)<-ebt[,1]
    ebt <- ebt[,c(colnames(ebt[grep(".*ref_hits", colnames(ebt))]))]
    bio_search_auto <- vector(mode = "list", length = length(input_biotype))
    names(bio_search_auto) <- unique(gsub(".*\\.(.+)\\..*", "\\1",colnames(ebt)))
    
    ebt$seq <- rownames(ebt)
    l_ebt <- reshape2::melt(ebt, id.vars="seq")
    l_ebt[,c("mismatch", "rna")] <- reshape2::colsplit(l_ebt$variable, "\\.",c("mismatch", "rna"))
    l_ebt$rna<-gsub("\\..*","",l_ebt$rna)
    l_ebt2 <- reshape2::dcast(l_ebt, seq + mismatch ~ rna, value.var="value")
    l_ebt2 <- l_ebt2[,-c(1:2)]
    
    for(i in 1:length(bio_search_auto)){
      rna_name <- unique(regmatches(l_ebt2[,i], regexpr("[A-Za-z]*RNA", l_ebt2[,i])))
      #if no hits are found, add name of reference instead
      if(length(rna_name)==0){rna_name <- names(l_ebt2)[i]}
      bio_search_auto[[i]] <- rna_name
      }
    
    nams <- as.character(lapply(bio_search_auto, unique))
    nams <- paste(nams, collapse=", ")
    
    cat(paste0("\nEstimation of biotypes in data have been done (if this was not intended, please rerun script with estimate_biotype=FALSE). Biotypes found in data: \n\n",
          (nams),
"\nIf you believe there are other biotypes that should be available from your references, please add a list manually with 'bio_search' (see ??add_reanno for details)\n"))
    
    #varför printas denna så konstigt 
    bio_search <- bio_search_auto
    
  }
  }
  
    
  #add biotype annotation
    if(!is.null(bio_search)){
      op <- add_reanno(reanno_biotype, type="biotype", mismatches = mismatches,
                       bio_search = bio_search, bio_perfect = FALSE)
    }
    
  #Add "full" annotation information
    if(save_name==TRUE){
      
      level_obj <- as.list(reanno_biotype@Full_anno)
      obj_names <- names(level_obj)
      obj_names <- obj_names[grepl("^mis\\d*$", obj_names)]
      
      if (length(obj_names) == 0) {
        stop("No mis-columns found on reanno object, please check whether mapping finalised correctly")
      }
      
      out_df <- data.frame(row.names = level_obj[[1]][[1]]$seq)
      all_df <- data.frame(row.names = level_obj[[1]][[1]]$seq)
      
      for (i in obj_names) {
        obj <- level_obj[[i]]
        list_names <- names(obj)
        
        for(j in list_names) {
          tib <- obj[[j]]
          if (ncol(tib) < 4) return(NULL)
          out <- tib[, 4, drop = FALSE]
          names(out) <- paste0(i, "_", j)
          out
          out_df <- cbind(out_df, out)
        }
        
        if(ncol(all_df)==0){
          all_df <- out_df
        }
        else{
          all_df <- cbind(all_df, out_df)
        }
      }
      
      if(!is.null(bio_search)){
        op <- cbind(op, all_df)
      }  else{
        op <- all_df
      }
      
    }
  
  
  #extract info about tRNA cleavage sites, if tRNAs were found
  
  if(any(grepl(".*tRNA.*", bio_search))){
    
    #find tRNA ref
    tRNA_ref <- bio_search[grep(".*tRNA.*", bio_search)]
    tRNA_ref <- input_biotype[names(tRNA_ref)]
    mp <- PAC_mapper(PAC, input=tRNA_ref[[1]], mismatches = mismatches, override = TRUE)
    tc <- tRNA_class(PAC, map=mp)
    tc_df <- tc$Anno[,c("class", "decoder", "acceptor","type")]
    mrg <- merge(x=PAC$Anno, y=tc_df, all.x=TRUE, all.y=FALSE, sort=F, by=0)
    mrg <- mrg[match(rownames(PAC$Anno),mrg$Row.names),]
    rownames(mrg) <- mrg$Row.names
    mrg <- mrg[,!names(mrg) %in% "Row.names"]
    PAC$Anno <- mrg
  }
  
 if(identical(rownames(PAC$Anno), rownames(op))==FALSE){
  warning("Something off in biotype annotation! Suggested route for troubleshooting; 
          go through the reanno workflow manually for biotypes.")
 }
 PAC$Anno <- cbind(PAC$Anno, op)
 
 }
  
  #end with a hierarchy - either user based or our best bet
  if(is.null(hierarchy)){
    pat <- paste(paste0('^', c("seq", "Any"), '$'), collapse='|')
    g <- grep(pat, colnames(PAC$Anno))
    g[1]<-g[1]+1
    g[2]<-g[2]-1
    biotypes_found<-colnames(PAC$Anno)[do.call(seq.int, as.list(g))]
    hierarchy=list(rRNA="rRNA|rrna", miRNA="miRNA|mirna|mir|miR", tRNA="tRNA|trna", piRNA="piRNA|piR|pirna")
    for(i in 1:length(hierarchy)){
      ifelse(any(grepl(hierarchy[i], biotypes_found)), hierarchy[i]<-hierarchy[i], hierarchy[i]<-NA)
    }
    hierarchy<-hierarchy[!is.na(hierarchy)]
    hier_print <- as.character(names(hierarchy))
    hier_print <- paste(hier_print, collapse=" -> ")
    cat(paste0("\n\nNo hierarchy was provided for biotype annotation. Based on the biotypes annotated in the data, the basic hierarchy of:\n\n",
               (hier_print),"\n\nwill be used. Other biotypes potentially present in this data will be annotated as 'Other'. 
You may also define a hierarchy manually if you wish to change this, check ?simplify_reanno for more details.\n"))
    
  }
  PAC <- simplify_reanno(input=PAC, hierarchy = hierarchy, mismatches = mismatches, merge_pac = TRUE)
  
  #return
  stopifnot(PAC_check(PAC))
  if(tp=="S4"){
    return(as.PAC(PAC))
  }else{
    return(PAC)
  }    
}




