#' Plots jitter plot from PAC object
#'
#' \code{PAC_jitter} Plots a jitter plot using the information in the Anno and
#' Counts tables in a PAC object.
#'
#' Given a PAC object with grouped summaries  the function will use column(s) in the Anno object to group
#' the Counts table by row and then plot a jitter plot based on 
#' 
#' @family PAC analysis
#'
#' @seealso \url{https://github.com/Danis102} for updates on the current
#'   package.
#'   
#' @param input PAC list-object containing Anno and a summary list-folder with
#'   summarized dataframe(s) for example generated by PAC_summary. The function
#'   can also be applied on a dataframe containing a column with annotation
#'   groupings (e.g. biotype) and a column with summarized data (e.g. log2 fold
#'   changes). Rows should be unique sequences as the rownames of a PAC summary
#'   object.
#'
#' @param summary_target List with: 1st object being a character vector of the
#'   target dataframe in summary and 2nd object being a character vector of the
#'   target column(s) in that dataframe. In case of input being a dataframe,
#'   summary_target can be a character vector indicating the column with the
#'   summarized data.
#'   
#' @param anno_target Character vector with the name of the target column in
#'   Anno or the name of the annotation column in case of input being a dataframe. 
#'
#' @param limits Integer vector with the y-limits to be parsed to ggplot2.
#'
#' @param ypos_n Integer setting the y position of the n counts to be parsed to
#'   ggplot2.
#'
#' @param colors Character vector with color codes to be parsed to ggplot2.
#'   
#' @return A plot-list object with jitter plots generated by ggplot2.
#'
#' @examples
#' 
#' library(seqpac)
#' load("/home/danis31/OneDrive/Programmering/Programmering/Pipelines/Drosophila/Pipeline_3.1/seqpac/dm_test_PAC.Rdata")
#' 
#' PAC_filt <- PAC_rpm(PAC_filt)
#' 
#' PAC_filt <- PAC_summary(PAC=PAC_filt, norm = "rpm", type = "log2FC", pheno_target=list("Method"))
#' PAC_filt <- PAC_summary(PAC=PAC_filt, norm = "rpm", type = "percentgrand", pheno_target=list("Method"))
#' 
#' 
#' hierarchy <- list( Mt_rRNA= "12S|16S|Mt_rRNA",
#'                 rRNA="5S|5.8S|18S|28S|S45|Ensembl_rRNA|rRNA_Other",
#'                 Mt_tRNA= "tRNA_mt-tRNA",
#'                tRNA="Ensembl_tRNA|tRNA_nuc-tRNA",
#'                miRNA="^miRNA|Ensembl_miRNA|Ensembl_pre_miRNA",
#'                piRNA="piRNA")
#'
#' PAC_filt <- simplify_reanno(PAC_filt, hierarchy=hierarchy, mismatches=0, bio_name="Biotypes_mis0", PAC_merge=TRUE)
#' 
#' 
#' plots_FC <- PAC_jitter(PAC_filt, summary_target=list("Log2FC_Method"), anno_target=list("Biotypes_mis0"))
#' plots_FCgrand <- PAC_jitter(PAC_filt, summary_target=list("Percdiffgrand_Method"), anno_target=list("Biotypes_mis0"))
#' 
#' 
#' plots_FC[[1]]
#' cowplot::plot_grid(plotlist=plots_FCgrand[1:9],nrow = 3, ncol = 3)
#'
#' @export
#'
PAC_jitter <- function(PAC, summary_target=NULL, anno_target=NULL, type="jitter", limits=NULL, ypos_n=NULL, colvec=NULL, box=TRUE){
                                        					require(ggplot2)
                                                  if(!PAC_check(PAC)){stop("Input was not a PAC object.")}
  
                                                  if(is.null(summary_target[[1]])){stop("Error: You need to specify a target in PAC$summary with summary_target.")}
                                                  if(is.null(names(PAC$summary[[summary_target[[1]]]]))){stop("You need to specify a valid summary_target.\n(Hint: Double check correct object name in PAC$summary or rerun the 'PAC_summary' function.)")}
                                                  if(length(summary_target)==1){summary_target[[2]] <- names(PAC$summary[[summary_target[[1]]]])}
                                                  
                                                  ann <- PAC$Anno
                                                  if(is.null(anno_target[[1]])){
                                                          warning("No anno_target was specified.\nJitter plot will not be devided into biotypes.")
                                                          ann$All <- "All"
                                                          anno_target <- list("All", "All")}
                                                  if(length(colnames(PAC$Anno)[anno_target[[1]]]) <1){stop("You need to specify a valid anno_target.\n(Hint: Double check correct column name in PAC$Anno.)")}
                                                  if(length(anno_target) ==1){anno_target[[2]] <- unique(PAC$Anno[,anno_target[[1]]])}
                                                  ann_filt <- ann[,anno_target[[1]]] %in% anno_target[[2]]
                                                  df <- PAC$summary[[summary_target[[1]]]]
                                                  df <- df[,colnames(df) %in% summary_target[[2]],drop=FALSE]
                                                  df <- df[ann_filt,,drop=FALSE]
                                                  ann <- ann[,anno_target[[1]], drop=FALSE]
                                                  ann <- ann[ann_filt,,drop=FALSE]
                                                  stopifnot(identical(rownames(ann), rownames(df))) 

                                        					if(grepl("percent", summary_target[[1]])){cutoff <- 100} else {cutoff <- 0}
                                                  perc_up <- aggregate(df, list(as.character(ann[,1])), function(x){ perc_up <- sum(as.numeric(x > 0))/length(x)
                                        							                                                                   perc_up <- round(perc_up, digits=3)*100
                                        							                                                                   return(perc_up)
                                        							                                                                  })
                                                  perc_up <-  perc_up[match(as.character(anno_target[[2]]), as.character(perc_up$Group.1)),]
                                        				## Make graphs
                                                    if(is.null(colvec)){
                                                          bio <- as.character(unique(ann[,1]))
                                                          n_extra  <- sum(bio %in% c("no_anno", "other"))
                                                          colfunc <- colorRampPalette(c("#094A6B", "#FFFFCC", "#9D0014"))
                                                          if(n_extra==1){colvec <- c(colfunc(length(bio)-1), "#6E6E6E")}
                                                          if(n_extra==2){colvec <- c(colfunc(length(bio)-2), "#6E6E6E", "#BCBCBD")}
                                                          if(n_extra==0){colvec <- colfunc(length(bio))}
                                                    }
                                        				   plt_lst <- as.list(1:ncol(df))
                                        				   names(plt_lst) <- colnames(df)
                                        				   plt_lst <- plt_lst[match(summary_target[[2]], names(plt_lst))]
                                        					 plot_lst <- lapply(plt_lst, function(num){ 
                                                                  data <- data.frame(biotype=ann[,1], values=df[,num])
                                                                  data$biotype <- factor(data$biotype, levels=anno_target[[2]])
                                                                  mima  <- c(min(data$values), max(data$values))
                                                                  max_lim <- max(sqrt(mima^2))*1.4
                                                                  if(is.null(ypos_n)){ypos_n <- max(sqrt(mima^2))*1.35}
                                                                  if(is.null(limits)){limits <- c((mima[1]*1.2),  max_lim)}
                                                                  if(is.null(limits)){limits <- c((mima[1]*1.2),  max_lim)}
                                                                  
                                                							    if(type=="jitter"){
                                                                  p <- ggplot(data, aes(x=biotype, y=values, col=biotype, fill=biotype))+
                                                								        geom_hline(yintercept=0, col="#707177", cex=0.6) +
                                                								        geom_jitter(position=position_jitter(0.2), cex=1.5)+
                                                	                      stat_summary(geom = "crossbar", fun.y=median, fun.ymax = median, fun.ymin = median, width=0.7, cex=0.4, position = "identity", col="Black") +
                                                												geom_text(stat="count", aes(label=paste0("n=",..count.., "\nup:", perc_up[,num+1], "%")), size=3.5, y=ypos_n, col="Black") +
                                                												labs(title=paste0(colnames(df)[num]) , x="Biotype" , y =  paste0(summary_target[[1]]) ) +
                                                												theme_classic()+
                                                												scale_y_continuous(limits =limits) +
                                                												theme(legend.position="none", axis.title.x = element_text(size=15), axis.text.x = element_text(angle = 45, hjust = 0.95, size=13), axis.title.y = element_text(size=15) ,  axis.text.y = element_text(size=13))+
                                                												scale_color_manual(values=colvec)
                                                								        #coord_flip()
                                                                  if(box==TRUE){
                                                                        p <- p+geom_boxplot(width=0.3, fill="white", col="black", alpha=0.7,  outlier.shape = NA)}

                                                							    }
                                                                  if(type=="violin"){
                                                                  p <- ggplot(data, aes(x=biotype, y=values, col=biotype, fill=biotype))+
                                                								        geom_hline(yintercept=0, col="#707177", cex=0.6) +
                                                								        geom_violin (width=0.9, trim=TRUE, scale="width", color="black")+
                                                	                      stat_summary(geom = "crossbar", fun.y=median, fun.ymax = median, fun.ymin = median, width=0.7, cex=0.4, position = "identity", col="Black") +
                                                                        geom_text(stat="count", aes(label=paste0("n=",..count.., "\nup:", perc_up[,num+1], "%")), size=3.5, y=ypos_n, col="Black") +
                                                												labs(title=paste0(colnames(df)[num]) , x="Biotype" , y =  paste0(summary_target[[1]]) ) +
                                                												theme_classic()+
                                                												scale_y_continuous(limits =limits) +
                                                												theme(legend.position="none", axis.title.x = element_text(size=15), axis.text.x = element_text(angle = 45, hjust = 0.95, size=13), axis.title.y = element_text(size=15) ,  axis.text.y = element_text(size=13))+
                                                												scale_fill_manual(values=colvec)
                                                								        #coord_flip() 
                                                                  if(box==TRUE){
                                                                        p <- p+geom_boxplot(width=0.3, fill="white", col="black", alpha=0.7,  outlier.shape = NA)}
                                                							    
                                                                      }
                                                                return(p)
                                        					            })
                                            return(plot_lst)
                                         }
