#' Plots jitter plot from PAC object
#'
#' \code{PAC_jitter} Plots a jitter plot using the information in the Anno and
#' Counts tables in a PAC object.
#'
#' Given a PAC object with grouped summaries  the function will use column(s) in the Anno object to group
#' the Counts table by row and then plot a jitter plot based on 
#' 
#' @family PAC analysis
#'
#' @seealso \url{https://github.com/Danis102} for updates on the current
#'   package.
#'   
#' @param input PAC list-object containing Anno and a summary list-folder with
#'   summarized dataframe(s) for example generated by PAC_summary. The function
#'   can also be applied on a dataframe containing a column with annotation
#'   groupings (e.g. biotype) and a column with summarized data (e.g. log2 fold
#'   changes). Rows should be unique sequences as the rownames of a PAC summary
#'   object.
#'
#' @param summary_target List with: 1st object being a character vector of the
#'   target dataframe in summary and 2nd object being a character vector of the
#'   target column(s) in that dataframe. In case of input being a dataframe,
#'   summary_target can be a character vector indicating the column with the
#'   summarized data.
#'   
#' @param anno_target Character vector with the name of the target column in
#'   Anno or the name of the annotation column in case of input being a dataframe. 
#'
#' @param limits Integer vector with the y-limits to be parsed to ggplot2.
#'
#' @param ypos_n Integer setting the y position of the n counts to be parsed to
#'   ggplot2.
#'
#' @param colors Character vector with color codes to be parsed to ggplot2.
#'   
#' @return A plot-list object with jitter plots generated by ggplot2.
#'
#' @examples
#' 
#' path="/data/Data_analysis/Projects/Drosophila/Other/IOR/Jan_IOR_200130/R_analysis_full/"
#' load(file=paste0(path, "PAC_all.Rdata"))
#' PAC_all <- PAC_rpm(PAC_all)
#' pheno_target = list("Method", c("IOR1_proto", "IOR1_tgirt"))
#' 
#' PAC_IOR1 <- PAC_filter(PAC_all, size = c(16, 45), threshold = 10, coverage = 50, type = "rpm", stat = TRUE, pheno_target = pheno_target, anno_target = NULL)
#' 
#'
#' 
#' PAC <- PAC_summary(PAC, norm = "rpm", type = "log2FC", pheno_target=list("Adapt", unique(PAC$Pheno$Adapt)))
#' plot_lst <- PAC_jitter(PAC, summary_target=list(", anno_target=, limits, ypos_n, colors="Black"
#'
#'
#' (import_lst$Sports_filtered$Calc$mean_Log2FC, FC_col="mean_FC", feat_col="Biotype", limits=c(-1.1, 1.05), Ypos_n=1.05, colors=rgb_vec_sports
#'
#'plot_lst  <- PAC_diversity(PAC, resample=10, steps=10, thresh=c(1,500), cumulative=TRUE, start_perc=1, threads=8)
#' cowplot::plot_grid(plot_lst$A,plot_lst$B)
#'
#' @export
#'
PAC_jitter <- function(input, summary_target, anno_target, limits, ypos_n, colors="Black"){
                                        					require(ggplot2)
                                                  if(class(input)=="data.frame"){df <- input}
                                                  if(class(input)=="list"){ 
                                                                              
                                                                            df <- data.frame(Anno==PAC$Anno[,anno_target])
                                                    
                                                    
                                                    input <- list(input=input)}
                                        					plot_lst <- list(NA)
                                        					for(i in 1:length(input)){
                                        							exp <- names(input)[i]
                                        							input[[i]] <- input[[i]][!is.na(input[[i]][, colnames(input[[i]])==FC_col]),]
                                        							if(i==length(input)){
                                        							  perc_up_agg <- aggregate(input[[i]][,FC_col], list(as.character(input[[i]][,feat_col])), function(x){ sum(as.numeric(x > 0))/length(x)})
                                        							  perc_up <- round(perc_up_agg$x, digits=3)*100
                                        							  perc_up <-  perc_up[match(as.character(levels(input[[i]][,feat_col])), as.character(perc_up_agg$Group.1))]
                                        								plot_lst[[i]] <- ggplot(input[[i]], aes_string(x=feat_col, y=FC_col, col=feat_col, fill=feat_col))+
                                        								        geom_hline(yintercept=0, col="#707177", cex=0.6) +
                                        								        geom_jitter(position=position_jitter(0.2), cex=1.5)+
                                        	                      stat_summary(geom = "crossbar", fun.y=median, fun.ymax = median, fun.ymin = median, width=0.7, cex=0.4, position = "identity", col="Black") +								  			
                                        								        geom_boxplot(width=0.3, fill="white", col="black", alpha=0.7,  outlier.shape = NA)+
                                        												geom_text(stat="count", aes(label=paste0("n=",..count.., "\nup:", perc_up, "%")), size=5, y=ypos_n, col="Black") +
                                        												labs(title=paste0(exp) , x="Biotype" , y = paste0(FC_col)) +
                                        												theme_classic()+
                                        												scale_y_continuous(limits =limits) +
                                        												theme(legend.position="none", axis.text.x = element_text(angle = 45, hjust = 0.95), axis.text.y = element_text(size=15), axis.title.y= element_blank())+
                                        												scale_color_manual(values=colors)
                                        								        #coord_flip()
                                        								names(plot_lst)[i] <- exp
                                        								} else {
                                        								plot_lst[[i]] <- ggplot(input[[i]], aes_string(x=feat_col, y=FC_col, fill=feat_col))+
                                        												geom_violin (width=0.9, trim=FALSE, scale="width")+
                                        												geom_boxplot(width=0.2, fill="white", outlier.shape = NA)+
                                        												geom_text(stat="count", aes(label=paste0("n=",..count..)), size=5, y=ypos_n) +
                                        												labs(title=paste0(exp) , x="Biotype" , y = paste0(FC_col)) +
                                        												geom_hline(yintercept=0)+
                                        												theme_classic()+
                                        												scale_y_continuous(limits = limits) +
                                        												theme(legend.position="none", axis.text.x = element_text(angle = 45, hjust = 0.95), axis.text.y = element_text(size=15), axis.title.y= element_blank())+
                                        												coord_flip()
                                        								names(plot_lst)[i] <- exp
                                        								}
                                        					}
                                        				return(plot_lst)
                                }
