#'Pie plot from PAC
#'
#'\code{PAC_pca} PAC principle component analysis.
#'
#'Given a PAC object the function will perform a principle component analysis
#'calling the PCA function in the FactoMineR package.
#'
#'@family PAC analysis
#'
#'@seealso \url{https://github.com/Danis102} for updates on the current package.
#'
#'@param PAC PAC-list object.
#'
#'@param type Character indicating what type of data to be used. If
#'  type="counts" the PCA will be conducted on the raw Counts. If type="rpm" the
#'  analysis will be done on rpm values returned from PAC_rpm function and
#'  stored in the norm folder of the PAC-list object.
#'
#'@param anno_target List with: 1st object being character vector of target
#'  column(s) in Anno, 2nd object being a character vector of the target
#'  biotype(s) in the target column (1st object). Important, the 2nd object is
#'  order sensitive, meaning that categories will appear in the same order in
#'  the pie. (default=NULL)
#'
#'
#'@param pheno_target List with: 1st object being character vector of target
#'  column(s) in Pheno, 2nd object being a character vector of the target
#'  group(s) in the target column (1st object). Important, the 2nd object is
#'  order sensitive, meaning that categories will appear in the same order in
#'  the pie. (default=NULL)
#'
#'
#'
#'@return A PCA list object generated by the PCA function in the FactoMineR
#'  package
#'
#' @examples
#'
#' ### Load data ###
#' path="/data/Data_analysis/Projects/Drosophila/Other/IOR/Joint_analysis/R_analysis/"
#' load(file=paste0(path, "PAC_all.Rdata"))
#'
#'
#'# First apply shallow counts filter, and then generate rpm on which rpm filter is applied.
#'
#' PAC_filt <- PAC_filter(PAC_all, size=c(16,45), threshold=10, coverage=5, type="counts", stat=FALSE, pheno_target=NULL, anno_target=NULL)
#' PAC_filt <- PAC_rpm(PAC_filt)
#' PAC_filt <- PAC_filter(PAC_filt, size=c(16,45), threshold=10, coverage=5, type="rpm", stat=FALSE, pheno_target=NULL, anno_target=NULL)
#'
#'pca_all_cnt <- PAC_pca(PAC_filt, type="counts")
#'pca_all_rpm <- PAC_pca(PAC_filt, type="rpm")
#'
#' groups <- paste(substr(PAC_filt$Pheno$SampleProject, 1, 3), PAC_filt$Pheno$Method, PAC_filt$Pheno$Method_tag, PAC_filt$Pheno$Tag, sep="_")
#' lab_df <- data.frame(lab=c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O"), fact=unique(groups))
#' labs <- as.character(lab_df$lab[match(groups, lab_df$fact)])
#' groups <- paste(labs, groups, sep="_")
#'
#' data.frame(lib_size=colSums(PAC_filt$Counts), group=groups)
#'
#' ggbiplot::ggbiplot(pcobj = pca_all_cnt, choices=c(1,2), scale = 0, obs.scale = 0, var.scale = 0, groups = groups, labels=labs, labels.size=5, ellipse = FALSE, var.axes = FALSE)
#' ggbiplot::ggbiplot(pcobj = pca_all_cnt, choices=c(1,3), scale = 0, obs.scale = 0, var.scale = 0, groups = groups, labels=labs, labels.size=5, ellipse = FALSE, var.axes = FALSE)
#' ggbiplot::ggbiplot(pcobj = pca_all_cnt, choices=c(2,3), scale = 0, obs.scale = 0, var.scale = 0, groups = groups, labels=labs, labels.size=5, ellipse = FALSE, var.axes = FALSE)
#'
#' ggbiplot::ggbiplot(pcobj = pca_all_rpm, choices=c(1,2), scale = 0, obs.scale = 0, var.scale = 0, groups = groups, labels=labs, labels.size=5, ellipse = FALSE, var.axes = FALSE)
#' ggbiplot::ggbiplot(pcobj = pca_all_rpm, choices=c(1,3), scale = 0, obs.scale = 0, var.scale = 0, groups = groups, labels=labs, labels.size=5, ellipse = FALSE, var.axes = FALSE)
#' ggbiplot::ggbiplot(pcobj = pca_all_rpm, choices=c(2,3), scale = 0, obs.scale = 0, var.scale = 0, groups = groups, labels=labs, labels.size=5, ellipse = FALSE, var.axes = FALSE)
#'
#' @export

PAC_pca <- function(PAC, type="counts", pheno_target=NULL, anno_target=NULL){
                                      if(type=="counts"){ data <- PAC$Counts }
                                      if(type=="rpm"){ data <- PAC$norm$rpm }    
  
                                      if(!is.null(pheno_target)){
                                                  phn_indx  <-  PAC$Pheno[,pheno_target[[1]]] %in% pheno_target[[2]]
                                                  PAC$Pheno <- PAC$Pheno[phn_indx,]
                                                  data <- data[,phn_indx]
                                                  }
                                      if(!is.null(anno_target)){
                                                  ann_indx <- PAC$Anno[,anno_target[[1]]] %in% anno_target[[2]]
                                                  PAC$Anno <- PAC$Anno[ann_indx,]
                                                  data <- data[ann_indx, ]
                                                  }
                                      stopifnot(identical(rownames(PAC$Anno), rownames(PAC$Counts)))
                                      stopifnot(identical(rownames(PAC$Pheno), colnames(PAC$Counts)))
                                      
                                      PCA_res <- FactoMineR::PCA(t(data), graph=FALSE)
                                      return(PCA_res)
                                      }